version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_ds_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: data_science_db
      MYSQL_USER: ds_user
      MYSQL_PASSWORD: ds_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
